name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Install toolchain
        run: |
          rustup toolchain install nightly
          rustup component add rustfmt --toolchain nightly
          rustup component add clippy --toolchain nightly
          rustup override set nightly

      - name: Run cargo clippy
        run: cargo +nightly clippy -- -D warnings

      - name: Run cargo fmt --check
        run: cargo +nightly fmt --all -- --check

      - name: Run cargo test
        run: cargo test
