name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Remove Pre-installed Rust
        run: |
          rustup toolchain remove stable
          rm -f /home/runner/.cargo/bin/rust-analyzer
          rm -f /home/runner/.cargo/bin/rustfmt
          rm -f /home/runner/.cargo/bin/cargo-fmt

      - name: Install Rust Nightly
        run: |
          rustup update nightly
          rustup default nightly
          rustup component add rustfmt --toolchain nightly
          rustup component add clippy --toolchain nightly

      - name: Get Rust Version
        run: echo "RUST_VERSION=$(rustc --version)" >> $GITHUB_ENV

      - name: Cache Cargo Registry and Build Outputs
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-${{ env.RUST_VERSION }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo clippy
        run: cargo +nightly clippy -- -D warnings

      - name: Run cargo fmt --check
        run: cargo +nightly fmt --all -- --check

      - name: Run cargo test
        run: cargo test
